### ISSUE TITLE
At the end of the run it just doesn't say the amount of secrets each guy did

### ISSUE THREAD

**Issue by lorke1** [BetterMap/BetterMap#45]
It broke like 3 weeks ago sadly
![image](https://github.com/BetterMap/BetterMap/assets/46537913/ac149493-07d0-4ca7-a9c1-564595f185d6)
and I did secrets so I know it is broken

**Comment by tenios-sb** [comment]
API key is invalid for the next 15 days, cant fix

**Comment by lorke1** [comment]
do you have an estimation on when it will be fixed?

**Comment by lorke1** [comment]
of wait nvm you said 15 days lol

**Comment by lorke1** [comment]
why is it invalid tho?

**Comment by tenios-sb** [comment]
Got banned, API key is bound to my account

**Comment by lorke1** [comment]
oh like developer api key?

**Comment by lorke1** [comment]
also why u got banned?

**Comment by tenios-sb** [comment]
Yeah, since I was the one that requested it.
Was being stupid and sent a copypasta with flagged words in public chat.

**Comment by lorke1** [comment]
oh damn but why you got banned instead of muted?

**Comment by tenios-sb** [comment]
https://knowyourmeme.com/memes/navy-seal-copypasta
IP => major chat infraction

**Comment by lorke1** [comment]
Oh so you didn't get banned?

**Comment by tenios-sb** [comment]
Nah Major Chat Infraction is the ban reason

**Comment by lorke1** [comment]
Oh that is a ban? that means you got muted a lot of times

**Comment by tenios-sb** [comment]
Nope, no prior mutes. They just take "doxxing" seriously and ban for it

**Comment by lorke1** [comment]
Oh damn so you got banned for a month and you'll be unbanned in 15 days?

**Comment by tenios-sb** [comment]
Yes
