### ISSUE TITLE
Problem with secrets solver

### ISSUE THREAD

**Issue by Sorky96** [BetterMap/BetterMap#48]
Hello. I have a problem with secret beams. They don't appear in full party, when running 4 ppl or less they work just fine. Something changed with it?

**Comment by Sorky96** [comment]
Here is hypixel thread:
https://hypixel.net/threads/help-me-plz-bettermap.5701384/

**Comment by UnclaimedBloom6** [comment]
This is fixed in the beta version. Get the role in #roles in the Discord server.
The source is on the [scanner branch](https://github.com/BetterMap/BetterMap/tree/scanner).
